---
version: "3"
networks:
  net_flaresolverr: null
  net_jackett: null
  net_sonarr: null
  net_sonarr_anime: null
  net_sonarr_hevc: null
  net_radarr: null
  net_radarr_hevc: null
  net_lidarr: null
  net_requestrr: null
  net_ombi: null
  net_sabnzbd: null
  net_prowlarr: null
  net_rutorrent: null
  net_watchtower: null
  net_portainer: null
  net_bazarr: null
  net_overseer: null
  net_notifiarr: null
  net_nzbhydra2: null
  net_readarr: null
  net_linkding: null
  net_calibre_svc: null
  net_calibre: null
  net_reciperr: null
volumes:
  vol_downloads:
    driver: local
    driver_opts:
      type: none
      device: /mnt/download
      o: bind
  vol_media:
    driver: local
    driver_opts:
      type: none
      device: /mnt/media
      o: bind
  vol_linkding:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/linkding
      o: bind
  vol_flaresolverr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/flaresolverr
      o: bind
  vol_jackett:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/jackett
      o: bind
  vol_sonarr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/sonarr
      o: bind
  vol_sonarr_anime:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/sonarr_anime
      o: bind
  vol_sonarr_hevc:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/sonarr_hevc
      o: bind
  vol_radarr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/radarr
      o: bind
  vol_radarr_hevc:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/radarr_hevc
      o: bind
  vol_lidarr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/lidarr
      o: bind
  vol_requestrr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/requestrr
      o: bind
  vol_ombi:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/ombi
      o: bind
  vol_sabnzbd:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/sabnzbd
      o: bind
  vol_prowlarr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/prowlarr
      o: bind
  vol_rutorrent:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/rutorrent
      o: bind
  vol_watchtower:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run//watchtower
      o: bind
  vol_nginx:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/nginx
      o: bind
  vol_portainer:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/portainer
      o: bind
  vol_bazarr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/bazarr
      o: bind
  vol_overseerr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/overseerr
      o: bind
  vol_notifiarr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/notifiarr
      o: bind
  vol_notifiarr_tmp:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/tmp/notifiarr
      o: bind
  vol_nzbhydra2:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/nzbhydra2
      o: bind
  vol_readarr:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/readarr
      o: bind
  vol_calibre:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/calibre
      o: bind
  vol_calibre_svc:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/run/calibre_svc
      o: bind
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - vol_nginx:/data
    networks:
      net_sonarr: null
      net_sonarr_anime: null
      net_sonarr_hevc: null
      net_sabnzbd: null
      net_prowlarr: null
      net_jackett: null
      net_bazarr: null
      net_portainer: null
      net_ombi: null
      net_lidarr: null
      net_radarr: null
      net_requestrr: null
      net_overseer: null
      net_notifiarr: null
      net_nzbhydra2: null
      net_radarr_hevc: null
      net_linkding: null
      net_readarr: null
      net_calibre_svc: null
      net_calibre: null
      net_reciperr: null
    labels:
      - com.centurylinklabs.watchtower.enable=true
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    networks:
      net_watchtower: null
    labels:
      - com.centurylinklabs.watchtower.enable=true
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      net_flaresolverr: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - AUTO_UPDATE=true
      - RUN_OPTS=run options here
    volumes:
      - vol_jackett:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      net_jackett: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_prowlarr:/config
    ports:
      - 9696:9696
    networks:
      net_prowlarr: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  readarr:
    container_name: readarr
    image: cr.hotio.dev/hotio/readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_downloads:/downloads
      - vol_readarr:/config
    networks:
      net_readarr: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_sonarr:/config
      - vol_media:/media
      - vol_downloads:/downloads
    networks:
      net_sonarr: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  sonarr_hevc:
    image: linuxserver/sonarr
    container_name: sonarr_hevc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_sonarr_hevc:/config
      - vol_media:/media
      - vol_downloads:/downloads
    networks:
      net_sonarr_hevc: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  sonarr_anime:
    image: linuxserver/sonarr
    container_name: sonarr_anime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_sonarr_anime:/config
      - vol_media:/media
      - vol_downloads:/downloads
    networks:
      net_sonarr_anime: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_radarr:/config
      - vol_media:/media
      - vol_downloads:/downloads
    networks:
      net_radarr: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_lidarr:/config
      - vol_media:/media
      - vol_downloads:/downloads
    networks:
      net_lidarr: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_ombi:/config
    networks:
      net_ombi: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  requestrr:
    image: lscr.io/linuxserver/requestrr:latest
    container_name: requestrr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_requestrr:/config
    networks:
      net_requestrr: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_bazarr:/config
      - vol_media:/media
    networks:
      net_bazarr: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_overseerr:/config
    networks:
      net_overseer: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    restart: always
    networks:
      net_notifiarr: null
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/machine-id:/etc/machine-id
      - vol_notifiarr:/config
      - vol_notifiarr_tmp:/var/run/utmp
    labels:
      - com.centurylinklabs.watchtower.enable=true
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_nzbhydra2:/config
      - vol_downloads:/downloads
    networks:
      net_nzbhydra2: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - vol_sabnzbd:/config
      - vol_downloads:/downloads
    networks:
      net_sabnzbd: null
    labels:
      - com.centurylinklabs.watchtower.enable=true
  radarr_hevc:
    image: linuxserver/radarr
    container_name: radarr_hevc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_radarr_hevc:/config
      - vol_media:/media
      - vol_downloads:/downloads
    networks:
      net_radarr: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  linkding:
    container_name: arr-linkding
    image: sissbruecker/linkding:latest
    volumes:
      - vol_linkding:/etc/linkding/data
    networks:
      net_linkding: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - TZ=Australia/Adelaide
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_calibre_svc:/config
    networks:
      net_calibre_svc: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - vol_calibre:/config
      - vol_media:/books
    networks:
      net_calibre: null
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
